services:
  app:
    build: .
    command: npm run start:docker
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672